fix(console): disable tui's default features (#16)
otherwise, `cargo check` fails on windows with errors like the following:
```
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> termion-1.5.6\src\lib.rs:27:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?