feat(console): emit a parse error a config file contains unknown fields (#330)
This work is related to https://github.com/tokio-rs/console/pull/320#issuecomment-1095416429
return error message if the config file includes unknown fields.  

reference: https://serde.rs/container-attrs.html#deny_unknown_fields

## test

console.toml

```toml
[charset]
lang = "en_us.UTF-8"
ascii_only = true

[colors]
enabled = true
palette = "all"
truecolor = true

[colors.enable]
durations = true 
terminated = true
unknown = true  # unknown field
```

```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/tokio-console`
Error: failed to parse ./console.toml

Caused by:
    unknown field `unknown`, expected `durations` or `terminated` for key `colors.enable` at line 10 column 1

Location:
    tokio-console/src/config.rs:388:14
```