chore: fix clippy::unnecessary_fallible_conversions warning (#507)
This fixes a new clippy lint added in 1.75. This warning is currently
causing CI failure:
https://github.com/tokio-rs/console/actions/runs/7437067584/job/20234273745?pr=506.

```
error: use of a fallible conversion when an infallible one could be used
   --> tokio-console/src/conn.rs:106:40
    |
106 |                         let endpoint = Endpoint::try_from(self.target.clone())?;
    |                                        ^^^^^^^^^^^^^^^^^^ help: use: `From::from`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_fallible_conversions
    = note: `-D clippy::unnecessary-fallible-conversions` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::unnecessary_fallible_conversions)]`
```