chore: bump direct dependencies to fix -Zdirect-minimal-versions
cfg-if:

    error: failed to select a version for `cfg-if`.
        ... required by package `ratatui-crossterm v0.1.2`
        ... which satisfies dependency `ratatui-crossterm = "^0.1.2"` of package `ratatui v0.30.2`
        ... which satisfies dependency `ratatui = "^0.30.2"` of package `tokio-console v0.1.14 (/Users/dtolnay/git/tokio-console/tokio-console)`
    versions that meet the requirements `^1.0.1` are: 1.0.4, 1.0.3, 1.0.1

    all possible versions conflict with previously selected packages

      previously selected package `cfg-if v1.0.0`
        ... which satisfies dependency `cfg-if = "^1.0.0"` of package `tokio-console v0.1.14 (/Users/dtolnay/git/tokio-console/tokio-console)`

    failed to select a version for `cfg-if` which could resolve this conflict

serde:

    error: failed to select a version for `serde_derive`.
        ... required by package `serde_core v1.0.220`
        ... which satisfies dependency `serde_core = "^1.0.220"` of package `time v0.3.47`
        ... which satisfies dependency `time = "^0.3.47"` of package `ratatui-widgets v0.3.2`
        ... which satisfies dependency `ratatui-widgets = "^0.3.2"` of package `ratatui v0.30.2`
        ... which satisfies dependency `ratatui = "^0.30.2"` of package `tokio-console v0.1.14 (/Users/dtolnay/git/tokio-console/tokio-console)`
    versions that meet the requirements `=1.0.220` are: 1.0.220

    all possible versions conflict with previously selected packages

      previously selected package `serde_derive v1.0.145`
        ... which satisfies dependency `serde_derive = "=1.0.145"` of package `serde v1.0.145`
        ... which satisfies dependency `serde = "^1.0.145"` of package `console-subscriber v0.5.0 (/Users/dtolnay/git/tokio-console/console-subscriber)`

    failed to select a version for `serde_derive` which could resolve this conflict